/* ══════════════════════════════════════════════════════
   categories.js
   Metadata om alle kategoriane i oppgåvebankane (v2).
   Brukt av systemprompten slik at LLMen berre vel
   kategorinøklar som faktisk finst i banken.
   ────────────────────────────────────────────────────
   Kvart objekt har:
     key        – same som `kat` i oppgavebank-v2.js
     label      – visingsnamn (same som `kat_label`)
     short      – kort, elevvennleg forklaring (8. klasse)
     examples   – typiske feil/teikn LLMen skal sjå etter
══════════════════════════════════════════════════════ */

const CATEGORIES = {
  nn: [
    { key: 'og_aa',             label: 'Og / å',              short: 'Når skal du skrive «og», og når skal du skrive «å»?',
      examples: 'Bland «og» og «å», t.d. «likar og danse» i staden for «likar å danse».' },
    { key: 'samansett',         label: 'Samansette ord',      short: 'Ord som høyrer saman skal skrivast i eitt ord.',
      examples: 'Delte ord: «jule middag», «brun ost», «lang tur» i staden for «julemiddag», «brunost», «langtur».' },
    { key: 'dobbel_konsonant',  label: 'Dobbel konsonant',    short: 'Når skal ein konsonant skrivast dobbelt?',
      examples: '«katen» (skal vere «katten»), «glas» brukt feil, manglar dobbel t/l/m/n.' },
    { key: 'kj_skj',            label: 'Kj / skj-lyden',      short: 'Blandar du kj-lyd og skj-lyd?',
      examples: '«skjekk» for «kjekk», «kjino» for «kino».' },
    { key: 'teiknsetting',      label: 'Teiknsetting',        short: 'Punktum, komma, stor og liten bokstav.',
      examples: 'Manglar punktum, for lange setningar utan komma, liten bokstav etter punktum.' },
    { key: 'ordklassar',        label: 'Ordklassar',          short: 'Kjenne att substantiv, verb, adjektiv osv.',
      examples: 'Feil form av verb eller adjektiv, feil bøying, svak forståing av ordklassar.' },
    { key: 'setningsbygging',   label: 'Setningsbygging',     short: 'Bygge heile og tydelege setningar.',
      examples: 'Setningsfragment, kjempelange setningar, manglar subjekt eller verb.' },
    { key: 'bindeord',          label: 'Bindeord',            short: 'Ord som bind saman setningar (og, men, fordi, derfor).',
      examples: 'Bruker same bindeord heile tida, eller ingen bindeord i det heile.' },
    { key: 'tekststruktur',     label: 'Tekststruktur',       short: 'Innleiing, hovuddel og avslutning.',
      examples: 'Teksten startar rett på, manglar avsnitt, ingen tydeleg avslutning.' },
    { key: 'kjeldebruk',        label: 'Kjeldebruk',          short: 'Korleis vise kvar du har informasjonen frå.',
      examples: 'Ingen kjelder, kopierer utan sitat, manglar kjeldeliste.' },
    { key: 'oppgavetolking',    label: 'Oppgåvetolking',      short: 'Svare på det oppgåva faktisk spør om.',
      examples: 'Svarar berre delvis på oppgåva, eller skriv om noko anna.' },
    { key: 'spraak_stil',       label: 'Språk og stil',       short: 'Passande språk for mottakar og sjanger.',
      examples: 'For munnleg språk i fagtekst, slang, gjentakingar, vage ord.' },
    { key: 'aarsak_samanheng',  label: 'Årsak og samanheng',  short: 'Vise kvifor ting heng saman.',
      examples: 'Listar fakta utan å forklare kvifor eller korleis.' },
    { key: 'referansekjede',    label: 'Referansekjede',      short: 'Halde styr på kven/kva du skriv om gjennom teksten.',
      examples: 'Uklare pronomen («han», «det») – lesaren veit ikkje kven det gjeld.' },
    { key: 'logisk_struktur',   label: 'Logisk struktur',     short: 'Rekkjefølgje som gjer at teksten heng saman.',
      examples: 'Hoppar mellom tema, gjentakingar, ulogisk rekkjefølgje.' },
    { key: 'sjangerkompetanse', label: 'Sjangerkompetanse',   short: 'Skrive i rett sjanger.',
      examples: 'Blandar novelle og fagtekst, feil form for sjangeren.' },
    { key: 'fagartikkel',       label: 'Fagartikkel',         short: 'Bygge opp ein fagartikkel.',
      examples: 'Manglar faktabasert språk, ingen innleiing eller konklusjon i fagartikkelen.' },
    { key: 'debattinnlegg',     label: 'Debattinnlegg',       short: 'Argumentere for eit syn.',
      examples: 'Manglar påstand, argument eller motargument.' },
    { key: 'overskrift_ingress',label: 'Overskrift og ingress', short: 'Lage tittel og ingress som fangar lesaren.',
      examples: 'Keisam eller uklar overskrift, manglar ingress.' },
    { key: 'novelle',           label: 'Novelle',             short: 'Bygge ei novelle med spenningskurve.',
      examples: 'Ingen konflikt, flat handling, ingen vending eller poeng.' },
    { key: 'parafrase',         label: 'Parafrase',           short: 'Gje att noko med eigne ord.',
      examples: 'Skriv av kjelda ordrett, eller endrar berre nokre ord.' },
    { key: 'sitat',             label: 'Sitat og sitatbruk',  short: 'Korleis bruke sitat riktig.',
      examples: 'Sitat utan hermeteikn eller kjelde, for lange sitat.' },
    { key: 'tal_og_statistikk', label: 'Tal og statistikk',   short: 'Bruke tal og statistikk i tekst.',
      examples: 'Tal utan kjelde, feil prosentrekning, ingen forklaring av tala.' },
    { key: 'djupneoppgaver',    label: 'Djupneoppgåver',      short: 'Større refleksjonsoppgåver.',
      examples: 'Brukast for elevar som treng ei større utfordring.' }
  ],

  bm: [
    { key: 'og_aa',             label: 'Og / å',              short: 'Når skal du skrive «og», og når skal du skrive «å»?',
      examples: 'Blander «og» og «å», f.eks. «liker og danse» i stedet for «liker å danse».' },
    { key: 'sammensatt',        label: 'Sammensatte ord',     short: 'Ord som hører sammen skal skrives i ett ord.',
      examples: 'Delte ord: «jule middag», «brun ost», «lang tur» i stedet for «julemiddag», «brunost», «langtur».' },
    { key: 'dobbel_konsonant',  label: 'Dobbel konsonant',    short: 'Når skal en konsonant skrives dobbelt?',
      examples: '«katen» (skal være «katten»), mangler dobbel t/l/m/n.' },
    { key: 'kj_skj',            label: 'Kj / skj-lyden',      short: 'Blander du kj-lyd og skj-lyd?',
      examples: '«skjekk» for «kjekk», «kjino» for «kino».' },
    { key: 'tegnsetting',       label: 'Tegnsetting',         short: 'Punktum, komma, stor og liten bokstav.',
      examples: 'Mangler punktum, for lange setninger uten komma, liten bokstav etter punktum.' },
    { key: 'ordklasser',        label: 'Ordklasser',          short: 'Kjenne igjen substantiv, verb, adjektiv osv.',
      examples: 'Feil form av verb eller adjektiv, feil bøying, svak forståelse av ordklasser.' },
    { key: 'setningsbygging',   label: 'Setningsbygging',     short: 'Bygge hele og tydelige setninger.',
      examples: 'Setningsfragment, kjempelange setninger, mangler subjekt eller verb.' },
    { key: 'bindeord',          label: 'Bindeord',            short: 'Ord som binder sammen setninger (og, men, fordi, derfor).',
      examples: 'Bruker samme bindeord hele tiden, eller ingen bindeord i det hele tatt.' },
    { key: 'tekststruktur',     label: 'Tekststruktur',       short: 'Innledning, hoveddel og avslutning.',
      examples: 'Teksten starter rett på, mangler avsnitt, ingen tydelig avslutning.' },
    { key: 'kildebruk',         label: 'Kildebruk',           short: 'Hvordan vise hvor du har informasjonen fra.',
      examples: 'Ingen kilder, kopierer uten sitat, mangler kildeliste.' },
    { key: 'oppgavetolking',    label: 'Oppgavetolking',      short: 'Svare på det oppgaven faktisk spør om.',
      examples: 'Svarer bare delvis på oppgaven, eller skriver om noe annet.' },
    { key: 'spraak_stil',       label: 'Språk og stil',       short: 'Passende språk for mottaker og sjanger.',
      examples: 'For muntlig språk i fagtekst, slang, gjentakelser, vage ord.' },
    { key: 'aarsak_sammenheng', label: 'Årsak og sammenheng', short: 'Vise hvorfor ting henger sammen.',
      examples: 'Lister fakta uten å forklare hvorfor eller hvordan.' },
    { key: 'referansekjede',    label: 'Referansekjede',      short: 'Holde styr på hvem/hva du skriver om gjennom teksten.',
      examples: 'Uklare pronomen («han», «det») – leseren vet ikke hvem det gjelder.' },
    { key: 'logisk_struktur',   label: 'Logisk struktur',     short: 'Rekkefølge som gjør at teksten henger sammen.',
      examples: 'Hopper mellom temaer, gjentakelser, ulogisk rekkefølge.' },
    { key: 'sjangerkompetanse', label: 'Sjangerkompetanse',   short: 'Skrive i riktig sjanger.',
      examples: 'Blander novelle og fagtekst, feil form for sjangeren.' },
    { key: 'fagartikkel',       label: 'Fagartikkel',         short: 'Bygge opp en fagartikkel.',
      examples: 'Mangler faktabasert språk, ingen innledning eller konklusjon i fagartikkelen.' },
    { key: 'debattinnlegg',     label: 'Debattinnlegg',       short: 'Argumentere for et syn.',
      examples: 'Mangler påstand, argument eller motargument.' },
    { key: 'overskrift_ingress',label: 'Overskrift og ingress', short: 'Lage tittel og ingress som fanger leseren.',
      examples: 'Kjedelig eller uklar overskrift, mangler ingress.' },
    { key: 'novelle',           label: 'Novelle',             short: 'Bygge en novelle med spenningskurve.',
      examples: 'Ingen konflikt, flat handling, ingen vending eller poeng.' },
    { key: 'parafrase',         label: 'Parafrase',           short: 'Gjengi noe med egne ord.',
      examples: 'Skriver av kilden ordrett, eller endrer bare noen ord.' },
    { key: 'sitat',             label: 'Sitat og sitatbruk',  short: 'Hvordan bruke sitat riktig.',
      examples: 'Sitat uten anførselstegn eller kilde, for lange sitater.' },
    { key: 'tal_og_statistikk', label: 'Tall og statistikk',  short: 'Bruke tall og statistikk i tekst.',
      examples: 'Tall uten kilde, feil prosentregning, ingen forklaring av tallene.' },
    { key: 'ordval',            label: 'Ordvalg og presisjon', short: 'Velge presise ord som passer.',
      examples: 'Vage ord som «ting», «sånn», «fin», gjentakelser, ord som ikke passer.' },
    { key: 'bruke_eksempel',    label: 'Bruke eksempler',     short: 'Støtte påstander med gode eksempler.',
      examples: 'Påstander uten eksempel, eller eksempel som ikke passer til påstanden.' },
    { key: 'tilpass_til_lesaren', label: 'Tilpass til leseren', short: 'Skrive slik at leseren forstår.',
      examples: 'Antar at leseren vet ting de ikke vet, bruker vanskelige ord uten å forklare.' },
    { key: 'djupneoppgaver',    label: 'Langsvar og refleksjonsoppgaver', short: 'Større refleksjonsoppgaver.',
      examples: 'Brukes for elever som trenger en større utfordring.' }
  ]
};

module.exports = { CATEGORIES };
